# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    blacklist:
        - ":kheldragar:"

services:
    gbslogistics.emotes.emote_bundle.emote_client:
        class: GbsLogistics\Emotes\EmoteBundle\SAEmoteCrawler
        arguments:
            - "%blacklist%"

    gbslogistics.emotes.emote_bundle.data_storage:
        class: GbsLogistics\Emotes\EmoteBundle\DataStorage
        arguments:
            - "%kernel.root_dir%/data"

    gbslogistics.emotes.emote_bundle.database_populator:
        class: GbsLogistics\Emotes\EmoteBundle\DatabasePopulator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gbslogistics.emotes.emote_bundle.data_storage"

    gbslogistics.emotes.emote_bundle.release_compiler:
        class: GbsLogistics\Emotes\EmoteBundle\ReleaseCompiler
        arguments:
            - "@gbslogistics.emotes.emote_bundle.entity.emote_repository"

    gbslogistics.emotes.emote_bundle.twig.emote_extension:
        class: GbsLogistics\Emotes\EmoteBundle\Twig\EmoteExtension
        public: false
        tags:
            - { name: twig.extension }

    gbslogistics.emotes.emote_bundle.website_assembler:
        class: GbsLogistics\Emotes\EmoteBundle\WebsiteAssembler
        arguments:
            - "@gbslogistics.emotes.emote_bundle.entity.history_repository"
            - "@templating"

    gbslogistics.emotes.s3Client:
        class: GbsLogistics\Emotes\S3Client
        arguments:
            - "%gbslogistics.emotes.s3bucket%"

    # Repositories
    gbslogistics.emotes.emote_bundle.entity.emote_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - "GbsLogistics\\Emotes\\EmoteBundle\\Entity\\Emote"

    gbslogistics.emotes.emote_bundle.entity.history_repository:
        class: GbsLogistics\Emotes\EmoteBundle\Entity\HistoryRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - "GbsLogistics\\Emotes\\EmoteBundle\\Entity\\History"

    # Releases
    gbslogistics.emotes.emote_bundle.release.pidgin:
        class: GbsLogistics\Emotes\EmoteBundle\Release\PidginRelease
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        tags:
            - { name: gbslogistics.emote_release, namespace: sagf_emote_pack }

    gbslogistics.emotes.emote_bundle.release.pidgin_nosmile:
        class: GbsLogistics\Emotes\EmoteBundle\Release\PidginNoSmileRelease
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        tags:
            - { name: gbslogistics.emote_release, namespace: sagf_emote_pack_nosmile }

    # Disposals
    gbslogistics.emotes.emote_bundle.artifact_disposal.noop:
        class: GbsLogistics\Emotes\EmoteBundle\ArtifactDisposal\NoopArtifactDisposal
        public: false

    gbslogistics.emotes.emote_bundle.artifact_disposal.unlink:
        class: GbsLogistics\Emotes\EmoteBundle\ArtifactDisposal\UnlinkArtifactDisposal
        public: false

    # Publishers
    gbslogistics.emotes.emote_bundle.publisher.noop:
        class: GbsLogistics\Emotes\EmoteBundle\Publisher\NoopPublisher
        public: false

    gbslogistics.emotes.emote_bundle.publisher.filesystem:
        class: GbsLogistics\Emotes\EmoteBundle\Publisher\FilesystemPublisher
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        public: false

    gbslogistics.emotes.emote_bundle.publisher.s3:
        class: GbsLogistics\Emotes\EmoteBundle\Publisher\S3Publisher
        arguments:
            - "@gbslogistics.emotes.s3Client"
        public: false

    # Distributions
    gbslogistics.emotes.emote_bundle.distribution.localhost:
        class: GbsLogistics\Emotes\EmoteBundle\Distribution\LocalhostDistribution
        arguments:
            - "%kernel.root_dir%/../web"
        public: false

    gbslogistics.emotes.emote_bundle.distribution.s3:
        class: GbsLogistics\Emotes\EmoteBundle\Distribution\S3Distribution
        arguments:
            - "@gbslogistics.emotes.s3Client"
        public: false
