# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    gbslogistics.emotes.emote_bundle.emote_client:
        class: GbsLogistics\Emotes\EmoteBundle\SAEmoteCrawler

    gbslogistics.emotes.emote_bundle.data_storage:
        class: GbsLogistics\Emotes\EmoteBundle\DataStorage
        arguments:
            - "%kernel.root_dir%/data"

    gbslogistics.emotes.emote_bundle.database_populator:
        class: GbsLogistics\Emotes\EmoteBundle\DatabasePopulator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gbslogistics.emotes.emote_bundle.data_storage"

    gbslogistics.emotes.emote_bundle.release_compiler:
        class: GbsLogistics\Emotes\EmoteBundle\ReleaseCompiler
        arguments:
            - "@gbslogistics.emotes.emote_bundle.entity.emote_repository"

    # Repositories
    gbslogistics.emotes.emote_bundle.entity.emote_repository:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
        arguments:
            - "GbsLogistics\\Emotes\\EmoteBundle\\Entity\\Emote"

    # Distributions
    gbslogistics.emotes.emote_bundle.release.pidgin:
        class: GbsLogistics\Emotes\EmoteBundle\Distribution\PidginRelease
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        tags:
            - { name: gbslogistics.emote_release, namespace: sagf_emote_pack }

    gbslogistics.emotes.emote_bundle.release.pidgin_nosmile:
        class: GbsLogistics\Emotes\EmoteBundle\Distribution\PidginNoSmileRelease
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        tags:
            - { name: gbslogistics.emote_release, namespace: sagf_emote_pack_nosmile }

    # Disposals
    gbslogistics.emotes.emote_bundle.artifact_disposal.noop:
        class: GbsLogistics\Emotes\EmoteBundle\ArtifactDisposal\NoopArtifactDisposal
        public: false

    gbslogistics.emotes.emote_bundle.artifact_disposal.unlink:
        class: GbsLogistics\Emotes\EmoteBundle\ArtifactDisposal\UnlinkArtifactDisposal
        public: false

    # Publishers
    gbslogistics.emotes.emote_bundle.publisher.noop:
        class: GbsLogistics\Emotes\EmoteBundle\Publisher\NoopPublisher
        public: false

    gbslogistics.emotes.emote_bundle.publisher.filesystem:
        class: GbsLogistics\Emotes\EmoteBundle\Publisher\FilesystemPublisher
        arguments:
            - "@gbslogistics.emotes.emote_bundle.data_storage"
        public: false
