# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    gbslogistics.emotes.emote_bundle.emote_client:
        class: GbsLogistics\Emotes\EmoteBundle\SAEmoteCrawler
    gbslogistics.emotes.emote_bundle.data_storage:
        class: GbsLogistics\Emotes\EmoteBundle\DataStorage
        arguments:
            - "%kernel.root_dir%/data"
    gbslogistics.emotes.emote_bundle.database_populator:
        class: GbsLogistics\Emotes\EmoteBundle\DatabasePopulator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gbslogistics.emotes.emote_bundle.data_storage"
